### ISSUE TITLE
example/cube.py AssertionError

### ISSUE THREAD

**Issue by Ubica** [bglgwyng/pyVulkan#11]
I ran into this error while trying to run your cube example. Not sure if it's my mistake or maybe code depends on older version of VulkanSDK. Maybe something else?
```
(venv-pyvulkan) (master)dalibor@COSMOS:~/EXPERIMENTS/pyvulkan/pyVulkan/examples$ python cube.py 
Traceback (most recent call last):
  File "cube.py", line 516, in <module>
    demo = Demo()
  File "cube.py", line 160, in __init__
    assert graphics_queue_node_index == present_queue_node_index
AssertionError
```

I'm using Python 3.5.2, VulkanSDK 1.0.30.0, Xubuntu 16.04, python3-sdl2
```
ii  python3-sdl2                                0.9.3+dfsg2-1                                 all          Python bindings to the SDL2 C-library (Python 3 build)
```

```
(venv-pyvulkan) ()dalibor@COSMOS:~/EXPERIMENTS/pyvulkan/VulkanSDK/1.0.30.0$ export VULKAN_SDK=$PWD/x86_64
(venv-pyvulkan) ()dalibor@COSMOS:~/EXPERIMENTS/pyvulkan/VulkanSDK/1.0.30.0$ export PATH=$VULKAN_SDK/bin:$PATH
(venv-pyvulkan) ()dalibor@COSMOS:~/EXPERIMENTS/pyvulkan/VulkanSDK/1.0.30.0$ export LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH
(venv-pyvulkan) ()dalibor@COSMOS:~/EXPERIMENTS/pyvulkan/VulkanSDK/1.0.30.0$ export VK_LAYER_PATH=$VULKAN_SDK/etc/explicit_layer.d
```

```
(venv-pyvulkan) (master)dalibor@COSMOS:~/EXPERIMENTS/pyvulkan/pyVulkan/examples$ pip freeze
cffi==1.8.3
decorator==4.0.10
ipython==5.1.0
ipython-genutils==0.1.0
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.9
ptyprocess==0.5.1
pycparser==2.17
Pygments==2.1.3
PySDL2==0.9.5
pyVulkan==0.9
simplegeneric==0.8.1
six==1.10.0
traitlets==4.3.1
wcwidth==0.1.7
```

**Comment by bglgwyng** [comment]
It's just a git mistake. I didn't know that I had merged test branch with cube things. I'll commit a valid cube example sooner or later.

**Comment by Ubica** [comment]
so previous cube commits should work?

**Comment by mackst** [comment]
If you want to run some samples with pyVulkan. You can try https://github.com/mackst/vulkan-tutorial.
I only test it on Win10 with python27. But it should not hard to modify it for Linux.
