### ISSUE TITLE
_vulkan.h heard file line separator issue at Windows platform 

### ISSUE THREAD

**Issue by mackst** [bglgwyng/pyVulkan#2]
The _vulkan.h heard file's line separator cause import module failure at Windows platform.

**Comment by latte10am** [comment]
Sorry for my late reply. I don't have any window machine which is compatiable with vulkan. So I can't test the full program, but I just checked that ffi.cdef call works properly, which means that parsing header was done. Could you send me the error message?

**Comment by mackst** [comment]
```python
Traceback (most recent call last):
  File "F:/coding/pythonProjects/vulkan_test_01/triangle_02.py", line 3, in <module>
    from pyVulkan import *
  File "F:\coding\pythonProjects\pyVulkan\pyVulkan\__init__.py", line 3, in <module>
    from ._vulkan import *
  File "F:\coding\pythonProjects\pyVulkan\pyVulkan\_vulkan.py", line 9, in <module>
    ffi.cdef(resource_string(__name__, "_vulkan.h"))
  File "F:\coding\venv\vulkan\lib\site-packages\cffi\api.py", line 105, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "F:\coding\venv\vulkan\lib\site-packages\cffi\api.py", line 119, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "F:\coding\venv\vulkan\lib\site-packages\cffi\cparser.py", line 299, in parse
    self._internal_parse(csource)
  File "F:\coding\venv\vulkan\lib\site-packages\cffi\cparser.py", line 304, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "F:\coding\venv\vulkan\lib\site-packages\cffi\cparser.py", line 262, in _parse
    self.convert_pycparser_error(e, csource)
  File "F:\coding\venv\vulkan\lib\site-packages\cffi\cparser.py", line 291, in convert_pycparser_error
    raise api.CDefError(msg)
cffi.api.CDefError: cannot parse "typedef long int ptrdiff_t;"
:2:28: Illegal character '\r'
```

**Comment by latte10am** [comment]
Sorry for my late reply. I remove every line breaks in the header file, because I couldn't make the same error occur like you showed. I think that it's the problem of different cffi implementations. If this patch solves your problem, please notice me.

**Comment by griffin2000** [comment]
The setup script should strip out the \r characters. I fixed this locally with:
dos2unix.exe < "pyVulkan\vulkan_win32_cffi.h" > "pyVulkan\vulkan_win32_cffi.h.cr"

Then replaced old version. with the .cr version
