### ISSUE TITLE
PyVulkan Import Error

### ISSUE THREAD

**Issue by Jordonbc** [bglgwyng/pyVulkan#5]
I seem to have an error while importing PyVulkan

```
Traceback (most recent call last):
  File "C:/Users/jordon/PycharmProjects/VulkanTest/test.py", line 1, in <module>
    import pyVulkan
  File "C:\Program Files\Python35\lib\site-packages\pyVulkan\__init__.py", line 3, in <module>
    from ._vulkan import *
  File "C:\Program Files\Python35\lib\site-packages\pyVulkan\_vulkan.py", line 39, in <module>
    _lib = ffi.dlopen('vulkan-1.dll')
  File "C:\Program Files\Python35\lib\site-packages\cffi\api.py", line 139, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Program Files\Python35\lib\site-packages\cffi\api.py", line 769, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Program Files\Python35\lib\site-packages\cffi\api.py", line 758, in _load_backend_lib
    return backend.load_library(name, flags)
OSError: cannot load library vulkan-1.dll: error 0x7e
```

**Comment by js78** [comment]
The error message is self explaining. You don't have the vulkan sdk https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers
