### ISSUE TITLE
error pyvulkan

### ISSUE THREAD

**Issue by kevinlllR** [bglgwyng/pyVulkan#6]
Traceback (most recent call last):
  File "pyvulkan.py", line 1, in <module>
    from pyVulkan import *
  File "/usr/local/lib/python2.7/dist-packages/pyVulkan/**init**.py", line 3, in <module>
    from ._vulkan import *
  File "/usr/local/lib/python2.7/dist-packages/pyVulkan/_vulkan.py", line 41, in <module>
    _lib = ffi.dlopen('libvulkan.so')
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 139, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 769, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 758, in _load_backend_lib
    return backend.load_library(name, flags)
OSError: cannot load library libvulkan.so: libvulkan.so: cannot open shared object file: No such file or directory

**Comment by js78** [comment]
The error message is self explaining. You don't have the vulkan sdk https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers
